
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.115.248:3306/oee?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  cache:
    type: redis
    redis:
      key-prefix: oee-
      time-to-live: 1d
  data:
    redis:
      host: 127.0.0.1
      port: 8252
      username: default
      password: 597235
      connect-timeout: 20s
      timeout: 5s
      database: 0